require "user.options"
require "user.keymaps"
require "user.plugins"
vim.cmd "colorscheme tokyonight"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
